#设置端口号
server:
  port: 9005

  ###设置项目名称(项目名称不能使用下横杠)  用于以后spring cloud服务的查找
spring:
  application:
    name: huahua-gathering
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.117.83:3306/huahua_gathering?characterEncoding=utf8
    username: root
    password: 123456
  redis:
    host: 192.168.118.129
    port: 6379

    #jpa的配置
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true


#日志级别
logging:
  level:
    root: info
